In [32]:
import tensorflow as tf
import keras as K
import numpy as np
import os
import cv2
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.preprocessing import image
from keras.preprocessing.image import load_img
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

print("TensorFlow Version:",tf.__version__)
print("Keras Version:",K.__version__)

TensorFlow Version: 2.8.0
Keras Version: 2.8.0


In [33]:
Animals_types = os.listdir('Animals//')
Animals_types
path = 'Animals//'

sizeExpected = 60

images = []
labels = []

for i in Animals_types:
    data_path = path + str(i)
    filenames = [i for i in os.listdir(data_path) if i.endswith('.jpg')]
    print(filenames)
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)
        img = cv2.resize(img,(sizeExpected, sizeExpected))
        images.append(img)
        labels.append(i)

images = np.array(images)
images = images.astype('float32')/255
images.shape

x = images
y = labels
print(y)
y_labelEncoder = LabelEncoder()
y = y_labelEncoder.fit_transform(y)
print(y)
x,Y = shuffle(x,y, random_state=1)
train_x, test_x, train_y, test_y = train_test_split(images, y, test_size=0.20, random_state=415)

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

['CAT1.jpg', 'CAT2.jpg']
['DOG 1.jpg', 'DOG 2.jpg']
['cats', 'cats', 'dogs', 'dogs']
[0 0 1 1]
(3, 60, 60, 3)
(3,)
(1, 60, 60, 3)
(1,)


In [34]:
classifier = Sequential()

In [35]:
classifier.add(Conv2D(32, (3, 3), input_shape = (60, 60, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
classifier.add(Conv2D(32, (3, 3), activation = tf.nn.relu))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
classifier.add(Flatten())
classifier.add(Dense(units = 128, activation = tf.nn.relu))
classifier.add(Dense(units = 2, activation = tf.nn.softmax))

In [36]:
classifier.add(Flatten(input_shape=(60,60,3)))
classifier.add(Dense(units = 128, activation = tf.nn.relu))
classifier.add(Dense(units = 2, activation = tf.nn.softmax))

In [37]:
classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [38]:
classifier.fit(train_x,train_y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 484ms/step - loss: 0.6986 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6856 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6761 - accuracy: 0.6667
Epoch 4/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6545 - accuracy: 1.0000
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6544 - accuracy: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6427 - accuracy: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6330 - accuracy: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6277 - accuracy: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6196 - accuracy: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6105 - accuracy: 1.0000
Epoch 11/100
1/1 [

In [56]:
image = load_img('algo3.jpg', target_size=(60,60))
image = np.array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))

[1 1 0 0]


In [57]:
result = classifier.predict(image)
print(result)

if(result[0][0] > result[0][1]):
    print("Gato")
else:
    print("Cachorro")


[[0.09929305 0.90070695]]
Cachorro
